/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 body.glb -t
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Layer_1: THREE.Mesh
    ['22_Buttocks']: THREE.Mesh
    ['15_Thighs']: THREE.Mesh
    ['06_Abdomen']: THREE.Mesh
    ['21_Lower_back']: THREE.Mesh
    ['20_Back']: THREE.Mesh
    ['11_Elbows']: THREE.Mesh
    ['12_Fore_arms']: THREE.Mesh
    ['14_Hand_palms']: THREE.Mesh
    ['13_Hand_back']: THREE.Mesh
    ['02_Face']: THREE.Mesh
    ['19_Feet']: THREE.Mesh
    ['17_Legs']: THREE.Mesh
    ['16_Knees']: THREE.Mesh
    ['18_Ankles']: THREE.Mesh
    ['07_Lower_abdomen']: THREE.Mesh
    ['08_Intimate_area']: THREE.Mesh
    ['03_Neck']: THREE.Mesh
    ['04_Shoulders']: THREE.Mesh
    ['09_Arm_pits']: THREE.Mesh
    ['05_Chest']: THREE.Mesh
    ['01_Scalp']: THREE.Mesh
    ['10_Upper_arms']: THREE.Mesh
    ['01_Scalp_1']: THREE.Mesh
    ['02_Face001']: THREE.Mesh
    SA_12_LIPS: THREE.Mesh
    SA_11_MOUTH: THREE.Mesh
    SA_03_EARS: THREE.Mesh
    SA_13_JAW: THREE.Mesh
    SA_09_NOSTRILS: THREE.Mesh
    SA_08_NOSE: THREE.Mesh
    SA_06_EYES: THREE.Mesh
    SA_07_EYELASHES: THREE.Mesh
    SA_05_EYELIDS: THREE.Mesh
    SA_04_EYEBROWS: THREE.Mesh
    SA_10_CHEEKS: THREE.Mesh
    SA_02_TEMPLES: THREE.Mesh
  }
  materials: {}
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/body.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Layer_1.geometry} material={nodes.Layer_1.material} />
      <mesh geometry={nodes['22_Buttocks'].geometry} material={nodes['22_Buttocks'].material} />
      <mesh geometry={nodes['15_Thighs'].geometry} material={nodes['15_Thighs'].material} />
      <mesh geometry={nodes['06_Abdomen'].geometry} material={nodes['06_Abdomen'].material} />
      <mesh geometry={nodes['21_Lower_back'].geometry} material={nodes['21_Lower_back'].material} />
      <mesh geometry={nodes['20_Back'].geometry} material={nodes['20_Back'].material} />
      <mesh geometry={nodes['11_Elbows'].geometry} material={nodes['11_Elbows'].material} />
      <mesh geometry={nodes['12_Fore_arms'].geometry} material={nodes['12_Fore_arms'].material} />
      <mesh geometry={nodes['14_Hand_palms'].geometry} material={nodes['14_Hand_palms'].material} />
      <mesh geometry={nodes['13_Hand_back'].geometry} material={nodes['13_Hand_back'].material} />
      <mesh geometry={nodes['02_Face'].geometry} material={nodes['02_Face'].material} />
      <mesh geometry={nodes['19_Feet'].geometry} material={nodes['19_Feet'].material} />
      <mesh geometry={nodes['17_Legs'].geometry} material={nodes['17_Legs'].material} />
      <mesh geometry={nodes['16_Knees'].geometry} material={nodes['16_Knees'].material} />
      <mesh geometry={nodes['18_Ankles'].geometry} material={nodes['18_Ankles'].material} />
      <mesh geometry={nodes['07_Lower_abdomen'].geometry} material={nodes['07_Lower_abdomen'].material} />
      <mesh geometry={nodes['08_Intimate_area'].geometry} material={nodes['08_Intimate_area'].material} />
      <mesh geometry={nodes['03_Neck'].geometry} material={nodes['03_Neck'].material} />
      <mesh geometry={nodes['04_Shoulders'].geometry} material={nodes['04_Shoulders'].material} />
      <mesh geometry={nodes['09_Arm_pits'].geometry} material={nodes['09_Arm_pits'].material} />
      <mesh geometry={nodes['05_Chest'].geometry} material={nodes['05_Chest'].material} />
      <mesh geometry={nodes['01_Scalp'].geometry} material={nodes['01_Scalp'].material} />
      <mesh geometry={nodes['10_Upper_arms'].geometry} material={nodes['10_Upper_arms'].material} />
      <mesh geometry={nodes['01_Scalp_1'].geometry} material={nodes['01_Scalp_1'].material} />
      <mesh geometry={nodes['02_Face001'].geometry} material={nodes['02_Face001'].material} />
      <mesh geometry={nodes.SA_12_LIPS.geometry} material={nodes.SA_12_LIPS.material} />
      <mesh geometry={nodes.SA_11_MOUTH.geometry} material={nodes.SA_11_MOUTH.material} />
      <mesh geometry={nodes.SA_03_EARS.geometry} material={nodes.SA_03_EARS.material} />
      <mesh geometry={nodes.SA_13_JAW.geometry} material={nodes.SA_13_JAW.material} />
      <mesh geometry={nodes.SA_09_NOSTRILS.geometry} material={nodes.SA_09_NOSTRILS.material} />
      <mesh geometry={nodes.SA_08_NOSE.geometry} material={nodes.SA_08_NOSE.material} />
      <mesh geometry={nodes.SA_06_EYES.geometry} material={nodes.SA_06_EYES.material} />
      <mesh geometry={nodes.SA_07_EYELASHES.geometry} material={nodes.SA_07_EYELASHES.material} />
      <mesh geometry={nodes.SA_05_EYELIDS.geometry} material={nodes.SA_05_EYELIDS.material} />
      <mesh geometry={nodes.SA_04_EYEBROWS.geometry} material={nodes.SA_04_EYEBROWS.material} />
      <mesh geometry={nodes.SA_10_CHEEKS.geometry} material={nodes.SA_10_CHEEKS.material} />
      <mesh geometry={nodes.SA_02_TEMPLES.geometry} material={nodes.SA_02_TEMPLES.material} />
    </group>
  )
}

useGLTF.preload('/body.glb')
